// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleWebAPI.Data;

namespace SimpleWebAPI.Migrations
{
    [DbContext(typeof(MainDBContext))]
    [Migration("20200507141415_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleWebAPI.Models.Entities.Category", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = new Guid("a2203b89-438c-4eb1-9444-e041b1f26321"),
                            Name = "Kitchewares"
                        },
                        new
                        {
                            ID = new Guid("3c339f1d-8c94-426d-91bd-4be8119d85e6"),
                            Name = "Gadgets and Electronics"
                        },
                        new
                        {
                            ID = new Guid("58e36022-c982-461f-a4f3-d45255a54c86"),
                            Name = "Gardening Tools"
                        },
                        new
                        {
                            ID = new Guid("ebef8c84-14f9-4902-870a-e0d0ef79f4f4"),
                            Name = "Sports Equipment"
                        },
                        new
                        {
                            ID = new Guid("8385e38d-5088-4a63-bf55-b4e21c88e1f7"),
                            Name = "Gaming"
                        });
                });

            modelBuilder.Entity("SimpleWebAPI.Models.Entities.Product", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = new Guid("68d48c29-efc0-4b66-a7cc-938974893a57"),
                            CategoryID = new Guid("8385e38d-5088-4a63-bf55-b4e21c88e1f7"),
                            Description = "Final Fantasy 7 Remake",
                            Image = "https://gadgetpilipinas.net/wp-content/uploads/2019/09/ff7remake1st.jpg",
                            Name = "FF7 Remake"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
