// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleWebAPI.Data;

namespace SimpleWebAPI.Migrations
{
    [DbContext(typeof(MainDBContext))]
    partial class MainDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SimpleWebAPI.Models.Entities.Category", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            ID = new Guid("b8fe3b7a-d2ca-4f47-a2dc-5d4a06e84a00"),
                            Name = "Kitchewares"
                        },
                        new
                        {
                            ID = new Guid("92946aeb-0e77-4dbf-992d-6d35551c03ed"),
                            Name = "Gadgets and Electronics"
                        },
                        new
                        {
                            ID = new Guid("8a3689c4-5664-46a3-8140-d33acf19f46f"),
                            Name = "Gardening Tools"
                        },
                        new
                        {
                            ID = new Guid("c7780694-87b7-4679-846c-055cef8dc5d7"),
                            Name = "Sports Equipment"
                        },
                        new
                        {
                            ID = new Guid("a7200bc4-9dc2-4b28-b74f-3fde7f50f42f"),
                            Name = "Gaming"
                        });
                });

            modelBuilder.Entity("SimpleWebAPI.Models.Entities.Product", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ID = new Guid("0e814ef5-e26e-4c0d-b748-c53de784bfba"),
                            CategoryID = new Guid("a7200bc4-9dc2-4b28-b74f-3fde7f50f42f"),
                            Description = "Final Fantasy 7 Remake",
                            Image = "https://gadgetpilipinas.net/wp-content/uploads/2019/09/ff7remake1st.jpg",
                            Name = "FF7 Remake"
                        });
                });

            modelBuilder.Entity("SimpleWebAPI.Models.Entities.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = new Guid("7f6d871b-3da5-4c32-af87-2ce45ca500be"),
                            Email = "user@useremail.com",
                            Password = "123password",
                            Username = "Weeddnim"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
